// program where the user has to guess a number generated by a program

function guessNumber() {
  // generating a random integer from 1 to 10
  const random = Math.floor(Math.random() * 10) + 1;

  // take input from the user
  let number = parseInt(document.getElementById("inputNumber").value);

  // take the input until the guess is correct
  while (number !== random) {
    number = parseInt(prompt("Wrong guess, try again: "));
  }

  // check if the guess is correct
  if (number == random) {
    let resultPrint = document.createElement("h2");
    resultPrint.textContent = `Congratulations, you have won, the selected number was ${random}`;
    document.body.appendChild(resultPrint);
  }
}
